Document: suchbuch
Title: Debian suchbuch Manual
Author: <insert document author here>
Abstract: This manual describes what suchbuch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/suchbuch/suchbuch.sgml.gz

Format: postscript
Files: /usr/share/doc/suchbuch/suchbuch.ps.gz

Format: text
Files: /usr/share/doc/suchbuch/suchbuch.text.gz

Format: HTML
Index: /usr/share/doc/suchbuch/html/index.html
Files: /usr/share/doc/suchbuch/html/*.html
